spring:
  application:
    name: billmytrip-backend
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/billmytrip
    username: billmytrip
    password: billmytrip
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      hibernate.format_sql: false
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true

server:
  port: 8080
  servlet:
    context-path: /api
  forward-headers-strategy: framework

billmytrip:
  jwt:
    secret: "change-me-in-prod-this-is-a-32-byte-secret-key-for-hs256!"
    expiration-minutes: 240

logging:
  level:
    online.billmytrip: INFO
    org.springframework.security: INFO
